spring:
  application:
    name: Eureka Server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 5000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    root: INFO